# Generated by Django 3.1.2 on 2020-11-23 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BiggApp', '0002_auto_20201116_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecommerce',
            name='mobile_no',
            field=models.CharField(default=1),
            preserve_default=False,
        ),
    ]
