# Generated by Django 3.1.2 on 2020-11-23 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BiggApp', '0003_ecommerce_mobile_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecommerce',
            name='mobile_no',
            field=models.CharField(max_length=100),
        ),
    ]
