# Generated by Django 3.1.2 on 2020-11-23 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BiggApp', '0004_auto_20201123_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecommerce',
            name='mobile_no',
            field=models.IntegerField(),
        ),
    ]
