# Generated by Django 3.1.2 on 2021-01-11 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BiggApp', '0008_auto_20201213_2139'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User', models.CharField(max_length=150)),
                ('product', models.CharField(max_length=150)),
            ],
        ),
    ]
