# Generated by Django 3.1.2 on 2021-01-11 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BiggApp', '0009_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cart',
        ),
    ]
